name = "Ramadan Minecraft 26"
author = "Arsalan and Bros"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9825763a81532b9e0e0677fd261eef78e5c57d191d322fe60dda870da7475578"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
