name = "Ramadan Minecraft 26"
author = "Arsalan and Bros"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ac4d7271fdf6e1ed62df78fa3966ce3ad5031c891ec3683b1267efddca38eb6"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
