name = "Ramadan Minecraft 26"
author = "Arsalan and Bros"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a8c6c4397144c0ca63638b2dc9970ef6fcdb022a02ac64685d796d7ba2fdfc17"

[versions]
forge = "47.4.16"
minecraft = "1.20.1"
